#!/usr/bin/env bash
# firewall.sh — default-deny inbound with nftables for the Kami GPU box (architecture §10.3; plan T0.2 step 2).
#
#   inbound:  lo · established/related · ICMP/ICMPv6 · everything on tailscale0 (SSH lives here and only here)
#             optional: Tailscale's own UDP port for direct peer paths (off by default; DERP relays work without it)
#   outbound: unrestricted (vLLM weights, npm, the twin, the platform, Cloudflare/Tailscale control planes)
#   forward:  Docker manages its own chains; our published ports are loopback-only so nothing reaches containers
#             from the WAN regardless. We still drop forwarded traffic that does not come from Docker's bridges.
#
# Usage: sudo ./firewall.sh [--dry-run] [--allow-tailscale-udp]
# Idempotent: writes /etc/nftables.conf and loads it atomically. Verify with `nft list ruleset` and, from
# outside the tailnet, `nmap -Pn <public ip>` → every port filtered (T0.2 done-when).
set -euo pipefail

DRY_RUN=0
TS_UDP=0
for a in "$@"; do
  case "$a" in
    --dry-run) DRY_RUN=1 ;;
    --allow-tailscale-udp) TS_UDP=1 ;;
    *) echo "unknown flag $a" >&2; exit 2 ;;
  esac
done

TS_IF="${TAILSCALE_IF:-tailscale0}"
CONF="${NFT_CONF:-/etc/nftables.conf}"

RULESET=$(cat <<EOF
#!/usr/sbin/nft -f
# generated by infra/box/firewall.sh — do not hand-edit; re-run the script
flush ruleset

table inet kami {
  chain input {
    type filter hook input priority 0; policy drop;

    iif "lo" accept
    ct state established,related accept
    ct state invalid drop

    ip protocol icmp icmp type { echo-request, destination-unreachable, time-exceeded, parameter-problem } accept
    ip6 nexthdr icmpv6 icmpv6 type { echo-request, destination-unreachable, packet-too-big, time-exceeded, parameter-problem, nd-neighbor-solicit, nd-neighbor-advert, nd-router-advert } accept

    # everything from the tailnet: SSH (22), and nothing else is listening on this interface anyway
    iifname "${TS_IF}" accept
$( if [ "$TS_UDP" = 1 ]; then echo '    udp dport 41641 accept comment "tailscale direct path (optional)"'; fi )

    # no public SSH, no 8000/8001/8642 from anywhere but lo — they are bound to 127.0.0.1 and dropped here too
    counter comment "dropped inbound"
  }

  chain forward {
    type filter hook forward priority 0; policy drop;
    ct state established,related accept
    iifname "docker0" accept
    iifname "br-*" accept
    counter comment "dropped forward"
  }

  chain output {
    type filter hook output priority 0; policy accept;
  }
}
EOF
)

if [ "$DRY_RUN" = 1 ]; then
  printf '%s\n' "$RULESET"
  exit 0
fi

if [ "$(id -u)" -ne 0 ]; then echo "run as root" >&2; exit 1; fi
command -v nft >/dev/null || { echo "nftables not installed (apt install nftables)" >&2; exit 1; }

# Refuse to lock ourselves out: the tailscale interface must exist before we drop everything else.
if ! ip link show "$TS_IF" >/dev/null 2>&1; then
  echo "interface $TS_IF not found — bring Tailscale up first (tailscale up --ssh), or set TAILSCALE_IF" >&2
  exit 1
fi

TMP=$(mktemp)
printf '%s\n' "$RULESET" > "$TMP"
nft -c -f "$TMP"                      # syntax check first
install -m 0644 "$TMP" "$CONF"
nft -f "$CONF"
rm -f "$TMP"
systemctl enable nftables >/dev/null 2>&1 || true
echo "nftables ruleset loaded from $CONF (inbound: lo, established, icmp, ${TS_IF}; everything else dropped)"
nft list chain inet kami input | sed 's/^/  /'
