// GENERATED by scripts/embed-schemas.ts — do not edit. Source of truth: schemas/*.json

export const FACTS_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://data.bioregionaltwin.org/schema/facts-1.0.json",
  "title": "Fact sheet (facts-1.0)",
  "description": "The set of atoms a text may cite. Emitted by the twin MCP (get_entity_status, get_place, ...) and by the twin's briefing generator; consumed by factguard. A number a model utters must match one of these atoms in the same turn.",
  "type": "object",
  "required": [
    "schema_version",
    "as_of",
    "atoms"
  ],
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "1.0"
    },
    "as_of": {
      "type": "string",
      "format": "date-time",
      "description": "When the fact sheet was assembled; weekday words in replies resolve against this instant in America/Denver."
    },
    "tree_generated_at": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "source_tool": {
      "type": [
        "string",
        "null"
      ],
      "description": "MCP tool name that produced these atoms"
    },
    "atoms": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "object",
            "required": [
              "kind",
              "value"
            ],
            "additionalProperties": false,
            "properties": {
              "kind": {
                "const": "number"
              },
              "value": {
                "type": "number"
              },
              "unit": {
                "type": [
                  "string",
                  "null"
                ],
                "description": "UCUM, e.g. [ft_i]3/s, Cel, [in_i], [acr_us].[ft_i], %, ug/m3, ppb, mg/L, uS/cm, m, ft, s"
              },
              "property": {
                "type": [
                  "string",
                  "null"
                ],
                "description": "twin property, e.g. discharge, stage, swe, reservoir_fill, pm25, dm"
              },
              "place_id": {
                "type": [
                  "string",
                  "null"
                ],
                "pattern": "^[a-z_]+/[a-z0-9-]+$"
              },
              "time": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time",
                "description": "the reading's time; REQUIRED in the same sentence when stale is true"
              },
              "stale": {
                "type": "boolean",
                "default": false
              },
              "staleness_s": {
                "type": [
                  "number",
                  "null"
                ]
              },
              "source_id": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "forecast": {
                "type": "boolean",
                "default": false
              },
              "label": {
                "type": [
                  "string",
                  "null"
                ]
              }
            }
          },
          {
            "type": "object",
            "required": [
              "kind",
              "value"
            ],
            "additionalProperties": false,
            "properties": {
              "kind": {
                "const": "time"
              },
              "value": {
                "type": "string",
                "format": "date-time"
              },
              "role": {
                "type": [
                  "string",
                  "null"
                ],
                "description": "reading_time | valid_until | as_of | period_end | deadline"
              },
              "place_id": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "property": {
                "type": [
                  "string",
                  "null"
                ]
              }
            }
          },
          {
            "type": "object",
            "required": [
              "kind",
              "id",
              "name"
            ],
            "additionalProperties": false,
            "properties": {
              "kind": {
                "const": "place"
              },
              "id": {
                "type": "string",
                "pattern": "^[a-z_]+/[a-z0-9-]+$"
              },
              "name": {
                "type": "string"
              },
              "aliases": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          },
          {
            "type": "object",
            "required": [
              "kind",
              "name"
            ],
            "additionalProperties": false,
            "properties": {
              "kind": {
                "const": "species"
              },
              "name": {
                "type": "string"
              },
              "scientific": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "note_path": {
                "type": [
                  "string",
                  "null"
                ],
                "description": "commons note the species came from (this turn)"
              }
            }
          },
          {
            "type": "object",
            "required": [
              "kind",
              "value",
              "of"
            ],
            "additionalProperties": false,
            "properties": {
              "kind": {
                "const": "count"
              },
              "value": {
                "type": "integer",
                "minimum": 0
              },
              "of": {
                "type": "string",
                "description": "what was counted, e.g. children, members, stale_readings, alerts"
              },
              "place_id": {
                "type": [
                  "string",
                  "null"
                ]
              }
            }
          },
          {
            "type": "object",
            "required": [
              "kind",
              "name",
              "value"
            ],
            "additionalProperties": false,
            "properties": {
              "kind": {
                "const": "enum"
              },
              "name": {
                "type": "string",
                "description": "e.g. drought_class, flood_category, source_status, mood"
              },
              "value": {
                "type": [
                  "string",
                  "integer"
                ]
              },
              "place_id": {
                "type": [
                  "string",
                  "null"
                ]
              }
            }
          }
        ]
      }
    }
  }
} as const;

export const IDS_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://data.bioregionaltwin.org/id/schema/place-1.0.json",
  "title": "Front Range identity registry entry",
  "description": "The ENTIRE coupling surface between the twin and Prism. One ID string, one schema, two URL templates. No shared database, no shared library, no runtime call in either direction.",
  "type": "object",
  "required": [
    "schema_version",
    "id",
    "kind",
    "name",
    "generated_at"
  ],
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "1.0"
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z_]+/[a-z0-9-]+$",
      "description": "Canonical ID, e.g. 'place/boulder-creek'. Immutable once published; aliased on rename; never reused."
    },
    "kind": {
      "type": "string",
      "enum": [
        "bioregion",
        "watershed",
        "stream_reach",
        "waterbody",
        "lake",
        "reservoir",
        "peak",
        "ridge",
        "trail",
        "protected_area",
        "forest_stand",
        "ecological_system",
        "monitoring_site",
        "municipality",
        "county",
        "fire_event",
        "flood_event",
        "restoration_site",
        "other"
      ]
    },
    "name": {
      "type": "string"
    },
    "huc12": {
      "type": "string",
      "pattern": "^[0-9]{12}$"
    },
    "bbox": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "minItems": 4,
      "maxItems": 4
    },
    "sensitivity": {
      "type": "string",
      "enum": [
        "public",
        "generalized"
      ]
    },
    "geometry_url": {
      "type": "string",
      "format": "uri"
    },
    "latest_url": {
      "type": "string",
      "format": "uri"
    },
    "twin_url": {
      "type": "string",
      "format": "uri"
    },
    "commons_url": {
      "type": "string",
      "format": "uri"
    },
    "sameAs": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "generated_at": {
      "type": "string",
      "format": "date-time"
    }
  }
} as const;

export const BINDING_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://data.bioregionaltwin.org/schema/place-set-binding-1.0.json",
  "title": "Place-set binding (place-set-binding-1.0)",
  "description": "A set of twin ids an entity senses through (architecture §3). A twin 'place set' document: it names twin ids, roles and needs, and knows nothing about the platform that holds it. URLs only — a binding stores no geometry.",
  "type": "object",
  "required": [
    "schema_version",
    "binding_version",
    "entity_id",
    "archetype",
    "anchor",
    "members",
    "watersheds",
    "needs",
    "frozen_at"
  ],
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "1.0"
    },
    "binding_version": {
      "type": "integer",
      "minimum": 0,
      "description": "Immutable per version; 0 is a proposal (resolve_entity on a twin id) that no steward has frozen."
    },
    "entity_id": {
      "type": "string",
      "pattern": "^entity/[a-z0-9-]+$"
    },
    "archetype": {
      "type": "string",
      "enum": [
        "creek",
        "watershed",
        "reservoir",
        "mountain",
        "bioregion"
      ]
    },
    "anchor": {
      "$ref": "#/$defs/twinId"
    },
    "stream_id": {
      "oneOf": [
        {
          "$ref": "#/$defs/twinId"
        },
        {
          "type": "null"
        }
      ]
    },
    "commons_handle": {
      "type": [
        "string",
        "null"
      ]
    },
    "members": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "id",
          "role"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "$ref": "#/$defs/twinId"
          },
          "role": {
            "type": "string",
            "enum": [
              "main_stem_gauge",
              "gauge",
              "snotel",
              "reservoir",
              "water_quality",
              "air",
              "weather",
              "other"
            ]
          }
        }
      }
    },
    "watersheds": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/twinId"
      }
    },
    "reach_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "boundary": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "geometry_urls": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uri"
          }
        }
      }
    },
    "needs": {
      "type": "array",
      "minItems": 1,
      "maxItems": 8,
      "items": {
        "type": "object",
        "required": [
          "need",
          "property",
          "places",
          "agg"
        ],
        "additionalProperties": false,
        "properties": {
          "need": {
            "type": "string",
            "pattern": "^[a-z][a-z0-9_]*$"
          },
          "property": {
            "type": "string"
          },
          "places": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/twinId"
            }
          },
          "agg": {
            "type": "string",
            "enum": [
              "single",
              "mean",
              "median",
              "min",
              "max",
              "mean_24h",
              "max_intersecting"
            ]
          },
          "weight": {
            "type": "number",
            "minimum": 0
          }
        }
      }
    },
    "membership_rule": {
      "type": [
        "string",
        "null"
      ]
    },
    "frozen_at": {
      "type": "string",
      "format": "date-time"
    },
    "reviewed_by": {
      "type": [
        "string",
        "null"
      ]
    },
    "twin_index_etag": {
      "type": [
        "string",
        "null"
      ]
    }
  },
  "$defs": {
    "twinId": {
      "type": "string",
      "pattern": "^[a-z_]+/[a-z0-9-]+$"
    }
  }
} as const;

