/**
 * Note templates for the `entities` vault (ADR-E08; §6.7 "Mirrored to
 * commons notes"). Each returns a `NoteSpec`: the path, the tag family
 * (set at create only — survey §7.5), the metadata (`place_id` = the binding
 * anchor, `generated_by: entity-agent`, Art. 50 marker), and the fenced
 * block. Humans write below the fence.
 *
 * Nothing here carries claimant PII, secrets, or geometry. Prose is CC BY-SA.
 */
import type { HealthSnapshot } from "@kami/needs";
import { describeDelta, type Delta } from "@/lib/deltas";
import { disclosureLabel } from "@/copy";
import { commonsLink } from "../links";

export type NoteKind = "page" | "state" | "memo" | "report" | "bounty";

export type NoteSpec = {
  path: string;
  kind: NoteKind;
  tags: string[];
  metadata: Record<string, unknown>;
  block: string;
};

export type EntityRef = { id: string; slug: string; name: string; archetype: string; anchor: string | null; binding_version: number | null };

export const GENERATED_BY = "entity-agent";

export function notePath(slug: string, kind: NoteKind, suffix?: string): string {
  const base = `entities/${slug}`;
  switch (kind) {
    case "page":
      return base;
    case "state":
      return `${base}/state/${suffix}`;
    case "memo":
      return `${base}/memos/${suffix}`;
    case "report":
      return `${base}/reports/${suffix}`;
    case "bounty":
      return `${base}/bounties/${suffix}`;
  }
}

export function tagsFor(kind: NoteKind): string[] {
  return ["entity", `entity/${kind}`];
}

export function baseMetadata(entity: EntityRef, kind: NoteKind, now: Date, extra: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    place_id: entity.anchor,
    entity_id: entity.id,
    entity_slug: entity.slug,
    entity_name: entity.name,
    archetype: entity.archetype,
    kind: `entity/${kind}`,
    generated_by: GENERATED_BY,
    ai_generated: true,
    binding_version: entity.binding_version,
    platform_synced_at: now.toISOString(),
    license: "CC BY-SA 4.0",
    ...extra,
  };
}

function line(s: string | null | undefined): string {
  return (s ?? "").replace(/\r?\n+/g, " ").trim();
}

const MOOD_WORDS: Record<HealthSnapshot["mood"], string> = {
  asleep: "asleep",
  content: "content",
  concerned: "concerned",
  distressed: "distressed",
  celebrating: "celebrating",
};

// ---------------------------------------------------------------------------
// entity/page
// ---------------------------------------------------------------------------

export type PageInput = {
  entity: EntityRef;
  voice_md: string | null;
  members: Array<{ id: string; role: string; name?: string }>;
  watersheds: string[];
  needs: Array<{ need: string; property: string; places: string[]; agg: string }>;
  snapshot: HealthSnapshot | null;
  page_url: string;
  /** a tkSafe excerpt of the anchor's commons note, or null */
  place_excerpt: string | null;
  now: Date;
  commons_base?: string;
};

export function entityPage(i: PageInput): NoteSpec {
  const e = i.entity;
  const lines: string[] = [];
  lines.push(`# ${e.name}`);
  lines.push("");
  lines.push(`> ${disclosureLabel(e.name, e.archetype)}`);
  lines.push("");
  lines.push(`**${e.name}** is a kami — an AI voice for the ${e.archetype}, built on public sensor data from the Front Range Bioregional Twin. Its page: ${i.page_url}`);
  if (i.voice_md) {
    lines.push("");
    lines.push("## Voice");
    lines.push("");
    lines.push(line(i.voice_md));
  }
  if (i.place_excerpt) {
    lines.push("");
    lines.push("## The place, as the commons describes it");
    lines.push("");
    lines.push(`> ${i.place_excerpt}`);
  }
  lines.push("");
  lines.push(`## Body (binding v${e.binding_version ?? "?"})`);
  lines.push("");
  if (e.anchor) lines.push(`Anchor: ${commonsLink(e.anchor, undefined, i.commons_base)}`);
  lines.push("");
  lines.push("Watersheds:");
  for (const w of i.watersheds) lines.push(`- ${commonsLink(w, undefined, i.commons_base)}`);
  lines.push("");
  lines.push(`Senses through ${i.members.length} twin places:`);
  for (const m of i.members) lines.push(`- ${m.name ? `${m.name} — ` : ""}\`${m.id}\` (${m.role})`);
  lines.push("");
  lines.push("Needs:");
  for (const n of i.needs) lines.push(`- ${n.need}: ${n.property} (${n.agg}${n.places.length ? ` over ${n.places.map((p) => `\`${p}\``).join(", ")}` : ""})`);
  if (i.snapshot) {
    lines.push("");
    lines.push(`## As of ${i.snapshot.as_of}`);
    lines.push("");
    lines.push(`Mood: **${MOOD_WORDS[i.snapshot.mood]}** — ${i.snapshot.mood_reason}.`);
    for (const n of i.snapshot.needs) lines.push(`- ${n.need}: ${n.label}`);
  }
  lines.push("");
  // No clock inside the fence: the block must be byte-identical when nothing changed,
  // or every weekly run would be a PATCH (the twin's stub rule, survey §7.6).
  lines.push("_Generated by the platform from public data. Humans may write below this block._");
  return {
    path: notePath(e.slug, "page"),
    kind: "page",
    tags: tagsFor("page"),
    metadata: baseMetadata(e, "page", i.now, { page_url: i.page_url, watersheds: i.watersheds, member_count: i.members.length, mood: i.snapshot?.mood ?? null }),
    block: lines.join("\n"),
  };
}

// ---------------------------------------------------------------------------
// entity/state — the weekly pulse roll-up
// ---------------------------------------------------------------------------

export type StatePulse = { at: string; woke: boolean; text: string | null; guard_result: string | null; deltas: Delta[] };

export type StateInput = {
  entity: EntityRef;
  week: string;
  from: string;
  to: string;
  pulses: StatePulse[];
  snapshot: HealthSnapshot | null;
  now: Date;
};

export function entityState(i: StateInput): NoteSpec {
  const e = i.entity;
  const woke = i.pulses.filter((p) => p.woke).length;
  const spoke = i.pulses.filter((p) => p.woke && p.text && p.guard_result !== "dropped");
  const notable = i.pulses.flatMap((p) => p.deltas.filter((d) => d.notable).map((d) => ({ at: p.at, d })));
  const lines: string[] = [];
  lines.push(`# ${e.name} — week ${i.week}`);
  lines.push("");
  lines.push(`> ${disclosureLabel(e.name, e.archetype)}`);
  lines.push("");
  lines.push(`Pulses ${i.from} → ${i.to}: ${i.pulses.length} recorded, ${woke} woke, ${spoke.length} with a released utterance.`);
  if (i.snapshot) {
    lines.push("");
    lines.push(`Latest mood: **${MOOD_WORDS[i.snapshot.mood]}** — ${i.snapshot.mood_reason} (as of ${i.snapshot.as_of}).`);
  }
  if (notable.length) {
    lines.push("");
    lines.push("## What changed");
    lines.push("");
    for (const n of notable) lines.push(`- ${n.at} — ${describeDelta(n.d)}`);
  }
  if (spoke.length) {
    lines.push("");
    lines.push("## What it said");
    lines.push("");
    for (const p of spoke) lines.push(`- ${p.at} — ${line(p.text)}`);
  }
  if (!notable.length && !spoke.length) {
    lines.push("");
    lines.push("A quiet week: no band changed, no alert started or ended, no gauge went quiet or came back.");
  }
  return {
    path: notePath(e.slug, "state", i.week),
    kind: "state",
    tags: tagsFor("state"),
    metadata: baseMetadata(e, "state", i.now, { week: i.week, from: i.from, to: i.to, pulses: i.pulses.length, woke, mood: i.snapshot?.mood ?? null }),
    block: lines.join("\n"),
  };
}

// ---------------------------------------------------------------------------
// entity/memo — the quarterly strategy
// ---------------------------------------------------------------------------

export type MemoInput = { entity: EntityRef; quarter: string; memo_md: string; ratified_at: string | null; comment_open_until: string | null; now: Date };

export function entityMemo(i: MemoInput): NoteSpec {
  const e = i.entity;
  const lines = [
    `# ${e.name} — strategy ${i.quarter}`,
    "",
    `> ${disclosureLabel(e.name, e.archetype)}`,
    "",
    i.ratified_at ? `Ratified by the guardians on ${i.ratified_at}.` : `Draft; open for comment${i.comment_open_until ? ` until ${i.comment_open_until}` : ""}.`,
    "",
    i.memo_md.trim(),
  ];
  return {
    path: notePath(e.slug, "memo", i.quarter),
    kind: "memo",
    tags: tagsFor("memo"),
    metadata: baseMetadata(e, "memo", i.now, { quarter: i.quarter, ratified_at: i.ratified_at, status: i.ratified_at ? "ratified" : "draft" }),
    block: lines.join("\n"),
  };
}

// ---------------------------------------------------------------------------
// entity/report — the public half of a donor report
// ---------------------------------------------------------------------------

export type ReportInput = { entity: EntityRef; month: string; public_md: string; now: Date };

export function entityReport(i: ReportInput): NoteSpec {
  const e = i.entity;
  const month = i.month.slice(0, 7);
  const lines = [`# ${e.name} — report ${month}`, "", `> ${disclosureLabel(e.name, e.archetype)}`, "", i.public_md.trim()];
  return {
    path: notePath(e.slug, "report", month),
    kind: "report",
    tags: tagsFor("report"),
    metadata: baseMetadata(e, "report", i.now, { month }),
    block: lines.join("\n"),
  };
}

// ---------------------------------------------------------------------------
// entity/bounty — spec, state, UIDs; never claimant PII
// ---------------------------------------------------------------------------

export type BountyInput = {
  entity: EntityRef;
  bounty: {
    id: string;
    title: string;
    why_md: string;
    deliverable_md: string;
    verification_tier: number;
    evidence_spec: unknown;
    cap_usdc: string;
    claim_limit: number;
    deadline: string | null;
    status: string;
    twin_refs: string[];
    prediction: unknown;
    spec_sha256: string;
    eas_uid_posted: string | null;
    created_at: string | null;
  };
  uids: Array<{ schema: string; uid: string }>;
  now: Date;
  commons_base?: string;
};

export function entityBounty(i: BountyInput): NoteSpec {
  const e = i.entity;
  const b = i.bounty;
  const lines: string[] = [];
  lines.push(`# Bounty: ${b.title}`);
  lines.push("");
  lines.push(`> ${disclosureLabel(e.name, e.archetype)}`);
  lines.push("");
  lines.push(`Status: **${b.status}** · tier ${b.verification_tier} · cap ${b.cap_usdc} USDC · claims ${b.claim_limit}${b.deadline ? ` · deadline ${b.deadline}` : ""}`);
  lines.push("");
  lines.push("## Why");
  lines.push("");
  lines.push(b.why_md.trim());
  lines.push("");
  lines.push("## Deliverable");
  lines.push("");
  lines.push(b.deliverable_md.trim());
  lines.push("");
  lines.push("## Evidence required");
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(b.evidence_spec ?? {}, null, 2));
  lines.push("```");
  if (b.prediction) {
    lines.push("");
    lines.push("## Prediction");
    lines.push("");
    lines.push("```json");
    lines.push(JSON.stringify(b.prediction, null, 2));
    lines.push("```");
  }
  lines.push("");
  lines.push("## Twin references");
  lines.push("");
  for (const id of b.twin_refs) lines.push(`- ${commonsLink(id, undefined, i.commons_base)}`);
  lines.push("");
  lines.push("## Record");
  lines.push("");
  lines.push(`- spec sha256: \`${b.spec_sha256}\``);
  if (b.eas_uid_posted) lines.push(`- BountyPosted: \`${b.eas_uid_posted}\``);
  for (const u of i.uids) lines.push(`- ${u.schema}: \`${u.uid}\``);
  return {
    path: notePath(e.slug, "bounty", b.id),
    kind: "bounty",
    tags: tagsFor("bounty"),
    metadata: baseMetadata(e, "bounty", i.now, {
      bounty_id: b.id,
      status: b.status,
      verification_tier: b.verification_tier,
      cap_usdc: b.cap_usdc,
      deadline: b.deadline,
      twin_refs: b.twin_refs,
      spec_sha256: b.spec_sha256,
      eas_uid_posted: b.eas_uid_posted,
      attestation_uids: i.uids.map((u) => u.uid),
      created_at: b.created_at,
    }),
    block: lines.join("\n"),
  };
}
