/**
 * Embeds `schemas/*.json` into `src/schemas.generated.ts` so the validator
 * works in the Worker bundle (no filesystem) and under `rootDir: src`.
 * `test/schemas.test.ts` asserts the embedded copies are identical to the files.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const files = {
  FACTS_SCHEMA: "facts-1.0.json",
  IDS_SCHEMA: "ids-schema-1.0.json",
  BINDING_SCHEMA: "place-set-binding-1.0.json",
} as const;

let out = "// GENERATED by scripts/embed-schemas.ts — do not edit. Source of truth: schemas/*.json\n\n";
for (const [name, file] of Object.entries(files)) {
  const json = JSON.parse(readFileSync(join(root, "schemas", file), "utf8"));
  out += `export const ${name} = ${JSON.stringify(json, null, 2)} as const;\n\n`;
}
writeFileSync(join(root, "src", "schemas.generated.ts"), out);
console.log("wrote src/schemas.generated.ts");
