export const grants = {
  title: "Grant rounds",
  intro: "Gather ideas for a shared purpose. Review applications, then bring selected work into the bounty process.",
  empty: "No grant rounds yet. A steward can open a round with a purpose, a budget and a closing date.",
  budgetNote: "The budget is a planning limit, not proof of available funds. Selection does not transfer money.",
  create: "Create a draft round",
  titleLabel: "Round name",
  purposeLabel: "Purpose and eligibility",
  budgetLabel: "Planning budget (USDC)",
  deadlineLabel: "Applications close",
  applicationLabel: "Your proposal",
  apply: "Apply to this round",
  paused: "This being is paused. Stewards can prepare drafts or close a round. Opening and applying resume after guardian approval and publication.",
  reviewNote: "Applications are reviewed by people. Any resulting bounty still needs its usual approvals, evidence and payment signatures.",
  status: { draft: "Draft", open: "Open for applications", closed: "Applications closed", archived: "Archived" } as Record<string, string>,
};

export const grantsBackendCopy = {
 notFound: "Being not found.",
 retired: "This being is retired.",
 paused: "This being is paused. Opening a round and accepting applications are disabled.",
 consultation: "Publish this being before opening a public grant round.",
 invalid: "Provide a title, purpose, positive budget with at most two decimal places, and a valid UTC deadline.",
 future: "The application deadline must be in the future.",
 roundNotFound: "Round not found for this being.",
 onlyDraft: "Only a draft round can be opened.",
 deadline: "The application deadline has passed.",
 transition: "This round cannot make that transition.",
 signInApply: "Sign in before applying.",
 notAccepting: "This round is not accepting applications.",
 ownProposal: "Choose your own open proposal for this being.",
 notPublic: "This being is not public.",
 signIn: "Sign in to manage or apply to a grant round.",
 unknown: "Unknown grant action.",
 applied: "Your proposal is linked to this round. This is an application, not an award.",
 updated: "Grant round updated. No funds were moved or reserved.",
 role: "An accepted guardian or steward role is required.",
 failed: "The round could not be updated. Please retry.",
};
