/** Copy for the steward's sensing setup and its server-side refusals. */
export const sensingCopy = {
    heading: "Connect this being’s senses",
    summary: (places: number, needs: number) => `${places} configured places · ${needs} need mappings`,
    unavailable: "Sensing configuration unavailable",
    binding: "Binding",
    notConfigured: "not configured",
    explanation: "Configured places include observation sites and watershed context. This is not a count of live sensors. Missing or stale readings remain unknown.",
    review: "Review configured places and need mappings",
    watershed: "Watershed context",
    latest: "Latest snapshot:",
    noSnapshot: "No computed needs snapshot yet.",
    warnings: "The twin reported these coverage warnings:",
    acknowledgeWarnings: "I reviewed and accept these coverage limitations.",
    acknowledge: "I reviewed these places and need mappings for this being.",
    validating: "Validating with the twin…",
    approve: "Validate and approve sensing",
    refreshing: "Reading the twin…",
    refresh: "Refresh needs",
    compute: "Compute first needs snapshot",
    invalid: "A valid sensing binding is needed before setup can continue.",
    roleRequired: "An accepted steward or platform administrator can approve sensing and refresh needs.",
    preservation: "Sensing setup preserves pause and consultation settings. Agent writes remain disabled while paused.",
    forbidden: "Only an accepted steward or platform administrator can manage sensing.",
    notFound: "Being not found.",
    changed: "The binding changed. Reload and review the current version.",
    checksum: "The binding is invalid or its checksum does not match. A steward must repair it first.",
    validationFailed: (errors: string[]) => `Twin validation failed: ${errors.join("; ")}`,
    warningReview: "The twin reported warnings. Review them before approving sensing.",
    retired: "This being is retired.",
    approveFirst: "Approve the sensing binding before computing needs.",
    throttled: "A refresh was already requested. Wait a minute before trying again.",
    refreshFailed: "The twin refresh did not complete. Check the binding and twin connection, then retry after a minute.",
    signIn: "Sign in as this being’s steward to manage sensing.",
    checkboxRequired: "Review the places and need mappings, then check the approval box.",
    unknownAction: "Unknown sensing action.",
    approved: "Sensing approved. Compute the first needs snapshot next.",
    refreshed: "Needs refreshed from the twin. Existing privacy and pause settings are preserved.",
    failed: "Sensing could not complete. Retry after checking the twin connection.",
};
