/**
 * The connect bundle: everything an agent needs, in one download.
 *
 * It is rendered from the same sources `provisionEntity` uses — the same hard
 * rules template, the same `renderSoul`, the same `entity_bindings` row, the
 * same canonical JSON — so a bundle and a deployed Hermes profile can never
 * disagree about what the kami is. `__tests__/bundle.test.ts` asserts the
 * `SOUL.md` in a bundle is byte-identical to the one provisioning writes.
 *
 * What is deliberately NOT in it: the token. `mcp.json` and `.env.example`
 * carry the env expansion `${PLATFORM_MCP_TOKEN}`, never a secret, because a
 * bundle is a file people email themselves, drop in a repo and paste into an
 * issue. The token is minted once, on the page, and shown once.
 */
import { readFile } from "node:fs/promises";
import path from "node:path";
import { and, desc, eq } from "drizzle-orm";
import { canonicalJson, type Binding } from "@kami/binding";
import type { DbOrTx } from "@/db/events";
import * as schema from "@/db/schema";
import { assertNoChainKey, ProvisionError } from "@/lib/provisioning";
import { loadHardRules, renderSoul } from "@/lib/summon/soul";
import { twinTargetFor } from "@/lib/summon/twin";
import { AUTH_HEADER_TEMPLATE, mcpEndpoint, SLUG_ENV_VAR, TOKEN_ENV_VAR } from "./endpoint";
import { TWIN_DEFAULT_TREE, TWIN_MCP_URL } from "./twin-tools";

/** The name an MCP client will see for each server. Stable: config files quote it. */
export const PLATFORM_SERVER_KEY = "kami-platform";
export const TWIN_SERVER_KEY = "bioregional-twin";

export type BundleFile = {
  /** path inside the archive, `/`-separated */
  path: string;
  content: string;
  /** one line: what this file is for. Rendered in the README and on the page. */
  purpose: string;
};

export type ConnectBundle = {
  slug: string;
  name: string;
  generated_at: string;
  endpoint: string;
  twin_base_url: string;
  binding_version: number | null;
  binding_review: string;
  soul_version: number;
  hard_rules_version: number;
  files: BundleFile[];
};

export type BundleOptions = { now?: Date; origin: string; hardRulesFile?: string };

/** The skill Hermes runs, copied verbatim so any agent can read the same instructions. */
export const SKILL_FILES = [
  "SKILL.md",
  "references/needs-model.md",
  "references/templates.md",
  "scripts/pulse_precheck.py",
] as const;

const TEMPLATES_REL = path.join("profiles", "templates");

/** The bundle could not be rendered because the server is missing a checked-in template. */
export class BundleError extends Error {
  override name = "BundleError";
}

/** Walk up from the working directory for `profiles/templates`, as `soul.ts` does. */
export function templatesDirCandidates(cwd: string = process.cwd()): string[] {
  const fromEnv = process.env.KAMI_PROFILE_TEMPLATES_DIR;
  const out = fromEnv ? [fromEnv] : [];
  let dir = path.resolve(cwd);
  for (let i = 0; i < 6; i++) {
    out.push(path.join(dir, TEMPLATES_REL));
    const up = path.dirname(dir);
    if (up === dir) break;
    dir = up;
  }
  return out;
}

async function readTemplate(rel: string): Promise<string> {
  const tried: string[] = [];
  for (const dir of templatesDirCandidates()) {
    const file = path.join(dir, rel);
    try {
      return await readFile(file, "utf8");
    } catch {
      tried.push(file);
    }
  }
  throw new BundleError(`bundle template ${rel} is not readable; tried ${tried.join(", ")}`);
}

/** The MCP client config stanza, in the shape clients consume (`mcpServers` map). */
export function mcpClientConfig(opts: { endpoint: string; twinBaseUrl: string; slug: string }): string {
  const config = {
    mcpServers: {
      [PLATFORM_SERVER_KEY]: {
        type: "http",
        url: opts.endpoint,
        headers: { Authorization: AUTH_HEADER_TEMPLATE },
      },
      [TWIN_SERVER_KEY]: {
        type: "http",
        url: TWIN_MCP_URL,
      },
    },
  };
  return `${JSON.stringify(config, null, 2)}\n`;
}

function readme(b: Omit<ConnectBundle, "files">, files: BundleFile[]): string {
  const list = files.map((f) => `| \`${f.path}\` | ${f.purpose} |`).join("\n");
  return `# ${b.name} — connect an agent

This bundle was generated by beings.earth on ${b.generated_at} for \`entity/${b.slug}\`.
It is everything an MCP-capable agent needs in order to speak for this place. It is
not a program: no code here runs on its own, and nothing in it can reach your agent.
The platform can only see what your agent does when it calls a tool.

## What is in it

| file | what it is for |
|---|---|
${list}

## Getting connected

1. Mint a token on \`${b.endpoint.replace(/\/mcp$/, "")}/e/${b.slug}/connect\`. It is shown once.
2. Put it in your agent's environment as \`${TOKEN_ENV_VAR}\` (and \`${SLUG_ENV_VAR}=${b.slug}\`).
   See \`.env.example\`. Nothing in this bundle contains the token, on purpose.
3. Merge \`mcp.json\` into your MCP client's configuration. The platform server is HTTP and
   carries your token; the public twin uses Streamable HTTP and needs no credential.
   Read the platform's \`get_entity_config\` first: it is the current binding, including review state,
   member place IDs, scope and need mappings. Compare its version with this bundle before using it.
   Then check the twin's \`list_datasets\` and \`get_place\` for the configured anchor.
   Use the platform's \`get_needs_snapshot\` for this being's configured pulse: the hosted
   twin does not load your private binding file or know your being's slug.
4. Give your agent \`SOUL.md\` as its system prompt or its top-level instructions, and
   \`skills/entity-steward/\` as a skill it can read.
5. Run a read-only first turn: refresh configuration and needs, read the anchor, and explain any
   pending review, missing snapshot, stale source or pause separately. Do not publish or start jobs.
   A working MCP connection does not establish that website chat or its fact guard is configured.

## Local or custom twin trees

The default MCP configuration reads the public production twin. The platform's configured
static tree is listed below; changing that tree does not reconfigure the hosted twin.
For a custom tree or local binding, build the twin's \`mcp/\` checkout and replace the
bioregional-twin entry using \`mcp.local.example.json\`. Set \`TWIN_MCP_STDIO_PATH\` to
its absolute \`mcp/dist/stdio.js\` path and \`TWIN_BINDING_PATH\` to this bundle's absolute
\`binding.json\` path. This package is not published to npm.
See https://bioregionaltwin.org/agent-api.md for the supported local build commands.

## What the agent must honour

\`SOUL.md\` opens with a platform-owned hard-rules block (version ${b.hard_rules_version}).
It is not advice and it is not editable — the same block is compiled into every profile this
platform deploys, and the gate in front of the model enforces the part of it that can be
enforced mechanically. In short:

- **Every number the agent says must have come back from a tool call in the same turn.** No
  memory, no arithmetic from an earlier turn, no rounding from the voice block. A sentence
  carrying a number that is not in this turn's tool results is dropped before anyone reads it.
- **It speaks *for* the place, never *as* it**, and it is not a person and not a legal person.
- **It never signs anything.** It may draft a bounty or propose a payout; two human guardians
  sign, or nothing happens.
- **Stale is a state, not a mood.** A gauge that stopped reporting means "I can't feel my
  gauge" — with the time of the last reading — never distress and never a guess.

If you change the hard-rules block, you are running something else. Say so; do not call it
this kami.

## Provenance

- binding v${b.binding_version ?? "—"} (${b.binding_review}) — the place-set this kami senses through
- soul v${b.soul_version}, hard rules v${b.hard_rules_version}
- twin tree: ${b.twin_base_url}
- platform MCP: ${b.endpoint}
`;
}

/** Everything in the bundle, rendered from the database and the checked-in templates. */
export async function buildConnectBundle(db: DbOrTx, slug: string, opts: BundleOptions): Promise<ConnectBundle> {
  const now = opts.now ?? new Date();
  const [entity] = await db.select().from(schema.entities).where(eq(schema.entities.slug, slug)).limit(1);
  if (!entity) throw new ProvisionError("not_found", `no entity with slug ${slug}`);

  // The same row provisioning renders: the pinned binding version, or the
  // latest when the entity pins none.
  const [bindingRow] = await db
    .select()
    .from(schema.entityBindings)
    .where(
      entity.bindingVersion === null
        ? eq(schema.entityBindings.entityId, entity.id)
        : and(eq(schema.entityBindings.entityId, entity.id), eq(schema.entityBindings.bindingVersion, entity.bindingVersion)),
    )
    .orderBy(desc(schema.entityBindings.bindingVersion))
    .limit(1);
  if (!bindingRow) throw new ProvisionError("no_binding", `entity ${slug} has no binding row to render`);

  const [soulRow] = await db
    .select()
    .from(schema.souls)
    .where(eq(schema.souls.entityId, entity.id))
    .orderBy(desc(schema.souls.soulVersion))
    .limit(1);
  if (!soulRow) throw new ProvisionError("no_soul", `entity ${slug} has no soul row to render`);

  const hardRules = await loadHardRules(opts.hardRulesFile);
  const soul = renderSoul(hardRules.block, soulRow.voiceMd, slug);
  const twin = await twinTargetFor(entity.id, { db });
  const endpoint = mcpEndpoint(opts.origin);
  const twinBaseUrl = twin.base_url || TWIN_DEFAULT_TREE;

  const files: BundleFile[] = [
    { path: "SOUL.md", content: soul, purpose: "the agent's instructions: the platform's locked hard rules, then this kami's voice block" },
    { path: "binding.json", content: `${canonicalJson(bindingRow.binding as unknown as Binding)}\n`, purpose: "the place-set this being senses through; local twin clients can load it explicitly" },
    { path: "mcp.json", content: mcpClientConfig({ endpoint, twinBaseUrl, slug }), purpose: "MCP client configuration for both servers; the token is an environment expansion, not a value" },
    { path: "mcp.local.example.json", content: JSON.stringify({ mcpServers: { [TWIN_SERVER_KEY]: {
      type: "stdio", command: "node",
      args: ["${TWIN_MCP_STDIO_PATH}", "--tree", twin.local_dir ?? twinBaseUrl, "--binding", "${TWIN_BINDING_PATH}"],
    } } }, null, 2) + "\n", purpose: "optional local-checkout twin configuration for a custom static tree or private binding" },
    { path: ".env.example", content: `# ${TOKEN_ENV_VAR} is minted on the connect page and shown once. Never commit a filled copy.\n# No chain key may ever live here: the agent does not sign (ADR-E05).\n${TOKEN_ENV_VAR}=\n${SLUG_ENV_VAR}=${slug}\n`, purpose: "the two environment variables an agent needs; fill the token in, keep it out of version control" },
  ];

  for (const rel of SKILL_FILES) {
    files.push({
      path: `skills/entity-steward/${rel}`,
      content: await readTemplate(path.join("skills", "entity-steward", rel)),
      purpose:
        rel === "SKILL.md"
          ? "how this kami does its recurring work: a pulse, a weekly bounty draft, a quarterly memo, a donor paragraph"
          : rel === "references/needs-model.md"
            ? "reference: how needs, moods and staleness are computed by code before the agent ever sees them"
            : rel === "references/templates.md"
              ? "reference: tested sentences to fall back on when composing prose is not safe"
              : "the pulse pre-check: decides whether anything changed enough to be worth waking the model",
    });
  }

  const meta = {
    slug,
    name: entity.name,
    generated_at: now.toISOString(),
    endpoint,
    twin_base_url: twinBaseUrl,
    binding_version: bindingRow.bindingVersion,
    binding_review: bindingRow.review,
    soul_version: soulRow.soulVersion,
    hard_rules_version: hardRules.version,
  };
  files.push({ path: "README.md", content: readme(meta, files), purpose: "this file: what each of the others is for and what the agent must honour" });

  // The same refusal provisioning applies: nothing that looks like a chain key
  // may leave the platform in a profile or a bundle (X.1).
  for (const f of files) assertNoChainKey(f.path, f.content);
  return { ...meta, files };
}

export function bundleFilename(slug: string, now: Date): string {
  return `kami-${slug}-connect-${now.toISOString().slice(0, 10)}.zip`;
}
